### ISSUE TITLE
I need help!

### ISSUE THREAD

**Issue by barosanu231** [9ggy/Roblox-Gambling-Token-Grabbers#4]
Hi,im new to exloiting/coding and I really wanna be able to use this,I have no idea what a webhook is and when I run the blox flip script it says syntax error or something,I tried editing the text and I put bloxflip.com as "Webhook link" and it gave me a weird file that if I opened it was like a pdf reader(i tried on a Windows 8 pc),and it just said the code in bloxflip.js.
If you have time i'd really apreciate it if you would give me a walkthrough or a guide.

**Comment by 9ggy** [comment]
# Hello, i would be happy to help!

By webhook, I mean a Discord webhook. There are tons of videos on YouTube teaching you how to make one.

#### PS: DM me on Discord if you need further help @camel#2363
